markdown: redcarpet
name: ODE Draft Digital Services Guide
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: RIODE
  url: https://github.com/401ode

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /images/ode.png
logoalt: ODE Logo

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
- text: User-Centered Design
  url: user-centered-design/
- text: Agile Development
  url: agile/
- text: Interoperability (APIs)
  url: interoperability/
- text: Security
      url: security/
      children:
        - text: Hosting
          url: hosting/
        - text: Encryption
          url: encryption/
        - text: Authentication
          url: auth/
        - text: Relevant Laws
          url: relevant-laws/
- text: Other Topics
  url: future-topics/
  children:
  - text: Accessibility/Section 508
      url: accessibility/section 508
  - text: Analytics
      url: analytics/
  - text: Copyright
      url: copyright/
  - text: Customer Service
      url: customer-service/
  - text: Design Standards
      url: design-standards/
  - text: Domains and Branding
      url: domains-and-branding/
  - text: Governance
      url: governance/
  - text: Information Quality
      url: information-quality/
  - text: Mandatory Content (incl. APRA)
      url: mandatory-content/
  - text: Mobile/Device-Agnostic
      url: mobile-device-agnostic/
  - text: Multilingual Websites
      url: multilingual-websites/
  - text: Open Government/Data/Content
      url: open-government-data-content/
  - text: Plain Writing
      url: plain-writing/
  - text: Privacy and Identity Management
      url: privacy-and-identity-management/
  - text: Prohibition-on-Advertising
      url: prohibition-on-advertising/
  - text: Records Management
      url: records-management/
  - text: Search
      url: search/
  - text: Technology Standards
      url: technology-standards/
  - text: Third-Party Services and Social Media
      url: third-party-services-and-social-media/

repos:
- name: ODE Draft Digital Services Guide
  description: Main repository
  url: https://github.com/401ode/draft-ds-guide

back_link:
  url: "https://github.com/401ode"
  text: ODE's Github Org.

google_analytics_ua:

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
