markdown: redcarpet
name: ODE Draft Digital Services Guide
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: RIODE
  url: https://github.com/401ode

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /images/ode.png
logoalt: ODE Logo

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: /
- text: User-Centered Design
  url: user-centered-design/
- text: Agile Development
  url: agile/
- text: Interoperability (APIs)
  url: interoperability/
- text: Security
  url: security/
  children:
  - text: Hosting
    url: hosting/
  - text: Encryption
    url: encryption/
  - text: Authentication
    url: auth/
  - text: Relevant Laws
    url: relevant-laws/
  - text: Authentication
    url: authentication/
    internal: true
- text: Accessibility/Section 508
  url: accessibility-section508/
  internal: true
- text: Third-Party Services and Social Media
  url: third-party-services-and-social-media/
  internal: true
- text: Future Topics
  url: future-topics/
  children:
  - text: Accessibility/Section 508
    url: accessibility/section 508
  - text: Future Topic!
    url: analytics/
  - text: Future Topic!
    url: copyright/
  - text: Customer Service
    url: customer-service/
  - text: Future Topic!
    url: design-standards/
  - text: Future Topic!
    url: domains-and-branding/
  - text: Future Topic!
    url: governance/
  - text: Future Topic!
    url: information-quality/
  - text: Future Topic!
    url: mandatory-content/
  - text: Future Topic!
    url: mobile-device-agnostic/
  - text: Future Topic!
    url: multilingual-websites/
  - text: Future Topic!
    url: open-government-data-content/
  - text: Future Topic!
    url: plain-writing/
  - text: Future Topic!
    url: privacy-and-identity-management/
  - text: Future Topic!
    url: prohibition-on-advertising/
  - text: Future Topic!
    url: records-management/
  - text: Future Topic!
    url: search/
  - text: Future Topic!
    url: technology-standards/
  - text: Third-Party Services and Social Media
    url: third-party-services-and-social-media/
  - text: Future Topic!
    url: customerservice/
    internal: true


repos:
- name: ODE Draft Digital Services Guide
  description: Main repository
  url: https://github.com/401ode/draft-ds-guide

back_link:
  url: "https://github.com/401ode"
  text: ODE's Github Org.

google_analytics_ua:

base_url: "https://401ode.github.io/draft-ds-guide/"

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
